# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Simple Actions 101

on:
  push:
    branches:
      - actions-demo
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     

      - name: Bash shell commands
        run: echo ${{ github.event_name }}
        echo ${{ github.workspace }}
        echo ${{ github.ref }}
    
